services:
  metrohook:
    image: metrolistgroup/metrohook
    container_name: metrohook
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHAT_ID: ""
      ADMIN_ID: ""
      GITHUB_REPO: "MetrolistGroup/Metrolist"
      AUTHORIZED_USERS: "NotGanxsh,mostafaalagamy"
      CHECK_INTERVAL: "300"
      COMMAND_CHECK_INTERVAL: "0.5"
      TIMEOUT: "10"
      STATE_FILE: "/app/data/last_id.txt"
      BACKGROUND_IMAGE: "background.png"
      FONT_FILE: "font.ttf"
      RIGHT_EDGE_X: "1240"
      TEXT_Y: "120"
      FONT_SIZE: "75"
      TEXT_COLOR: "#e2e3e8"
      LOG_LEVEL: "INFO"
    volumes:
      - ./data:/app/data
